# Generated by Django 5.0.6 on 2024-09-01 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('group_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники группы')),
            ],
            options={
                'verbose_name': 'Группа Пользователей',
                'verbose_name_plural': 'Группы Пользователей',
            },
        ),
    ]
