# Generated by Django 5.0.6 on 2024-09-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupusers',
            name='discraption',
            field=models.CharField(default=2, max_length=250, verbose_name='Описание группы'),
            preserve_default=False,
        ),
    ]
