# Generated by Django 5.0.6 on 2024-09-04 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_groupusers_discraption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupusers',
            name='admin_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_group', to=settings.AUTH_USER_MODEL, verbose_name='Админ групп'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupusers',
            name='group_user',
            field=models.ManyToManyField(related_name='user_group', to=settings.AUTH_USER_MODEL, verbose_name='Участники группы'),
        ),
    ]
