# Generated by Django 5.0.6 on 2024-09-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_groupusers_admin_user_alter_groupusers_group_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupusers',
            old_name='discraption',
            new_name='description',
        ),
    ]
