# Generated by Django 5.0.6 on 2024-09-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeNewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(verbose_name='Тема')),
                ('text_info', models.TextField(verbose_name='Описание темы(текст)')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Дата создания темы')),
            ],
            options={
                'verbose_name': 'Тема для главной страницы',
                'verbose_name_plural': 'Темы для главной страницы',
            },
        ),
    ]
