# Generated by Django 5.0.6 on 2024-09-01 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeskModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100, verbose_name='Имя задания')),
                ('color_border', models.CharField(choices=[('red', 'красный'), ('blue', 'синий'), ('green', 'зеленый'), ('black', 'черный')], verbose_name='Цвет')),
                ('color_text', models.CharField(choices=[('red', 'красный'), ('blue', 'синий'), ('green', 'зеленый'), ('black', 'черный')], verbose_name='Цвет')),
                ('color_background', models.CharField(choices=[('red', 'красный'), ('blue', 'синий'), ('green', 'зеленый'), ('black', 'черный')], verbose_name='Цвет')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Дата создания задания')),
                ('text_info', models.TextField(max_length=1000, verbose_name='Информация о задание')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания ',
            },
        ),
        migrations.CreateModel(
            name='TemaModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название темы')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.groupusers', verbose_name='Група  которая имеет эту тему')),
                ('task', models.ManyToManyField(to='todo_table.teskmodels', verbose_name='Задания относящиеся к этой теме ')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
    ]
