# Generated by Django 5.0.6 on 2024-09-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teskmodels',
            name='color_background',
            field=models.CharField(choices=[('red', 'красный'), ('blue', 'синий'), ('green', 'зеленый'), ('white', 'белый'), ('black', 'черный')], verbose_name='Цвет_заднегофона'),
        ),
        migrations.AlterField(
            model_name='teskmodels',
            name='color_border',
            field=models.CharField(choices=[('red', 'красный'), ('blue', 'синий'), ('green', 'зеленый'), ('white', 'белый'), ('black', 'черный')], verbose_name='Цвет_обводки'),
        ),
        migrations.AlterField(
            model_name='teskmodels',
            name='color_text',
            field=models.CharField(choices=[('red', 'красный'), ('blue', 'синий'), ('green', 'зеленый'), ('white', 'белый'), ('black', 'черный')], verbose_name='Цвет_текста'),
        ),
    ]
