# Generated by Django 5.0.6 on 2024-09-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_table', '0003_rename_data_teskmodels_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeskModels',
            new_name='TaskModels',
        ),
    ]
