# Generated by Django 5.0.6 on 2024-09-12 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_table', '0004_rename_teskmodels_taskmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temamodels',
            name='task',
        ),
        migrations.AddField(
            model_name='taskmodels',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo_table.temamodels', verbose_name='Задания относящиеся к этой теме'),
            preserve_default=False,
        ),
    ]
